# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
        exclude: ^helm/templates/
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: file-contents-sorter
        files: ^requirements(-dev)?\.in$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
    - id: ruff-format
      name: Ruff format
      description: "Run 'ruff format' for extremely fast Python formatting"

    - id: ruff
      name: Ruff check
      description: "Run 'ruff check' for extremely fast Python linting"
      args: [ --fix ]
