version: "3.9"
services:
  app:
    build: .
    image: surajsubramanian/emotiondetection
    container_name: emotiondetection-run
    command: ["python", "main.py", "-i", "/tests/inputs/input.mp4", "-o", "/tests/outputs/output.mp4"]
    volumes:
      - type: bind
        source: ./tests/
        target: /tests/
